// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"bedrock/internal/repository"
	"bedrock/internal/repository/cache"
	"bedrock/internal/repository/dao"
	"bedrock/internal/service"
	"bedrock/internal/web"
	"bedrock/internal/web/middleware/jwt"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitUserHandler() *web.UserHandler {
	logger := InitLogger()
	db := InitMySQL()
	userDAO := dao.NewGORMUserDAO(db)
	cmdable := InitRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache, logger)
	userService := service.NewUserService(logger, userRepository)
	codeService := InitCodeService()
	provider := InitStorageService()
	handler := jwt.NewRedisJWTHandler(cmdable)
	userHandler := web.NewUserHandler(logger, userService, codeService, provider, handler)
	return userHandler
}

func InitWebServer() *gin.Engine {
	logger := InitLogger()
	db := InitMySQL()
	userDAO := dao.NewGORMUserDAO(db)
	cmdable := InitRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache, logger)
	userService := service.NewUserService(logger, userRepository)
	codeService := InitCodeService()
	provider := InitStorageService()
	handler := jwt.NewRedisJWTHandler(cmdable)
	userHandler := web.NewUserHandler(logger, userService, codeService, provider, handler)
	engine := InitGinServer(userHandler, handler)
	return engine
}

// wire.go:

var thirdParty = wire.NewSet(
	InitLogger,
	InitMySQL,
	InitRedis,
	InitStorageService,
	InitCodeService,
)

var userSvc = wire.NewSet(cache.NewRedisUserCache, dao.NewGORMUserDAO, repository.NewCachedUserRepository, service.NewUserService)
